<?xml version="1.0"?>
<!DOCTYPE section [
 <!ENTITY % entities SYSTEM "entities.ent"> %entities;
]>
<section xmlns="http://docbook.org/ns/docbook" xmlns:xi="http://www.w3.org/2001/XInclude"
        xmlns:xlink="http://www.w3.org/1999/xlink" xml:id="troubleshootingHeat">
 <title>Heat 故障排除</title>
 <para>
  Heat 服务的故障排除场景和解决办法。本页介绍 Heat 的故障排除方案。
 </para>
 <section xml:id="rpc.timeout.heat">
  <title>Heat 堆栈创建时 RPC 超时</title>
  <para>
   如果在尝试 Heat 堆栈创建时遇到远程过程调用（RPC）超时故障，可以通过增加超时值并从数据库中清除已删除堆栈的记录来解决此问题。为此，请按照以下步骤操作。以下是一个发送错误的例子：
  </para>
<screen>MessagingTimeout: resources.XXX-LCP-Pair01.resources[0]: Timed out waiting for a reply to message ID e861c4e0d9d74f2ea77d3ec1984c5cb6</screen>
  <procedure>
   <step>
    <para>
     增加超时值。
    </para>
<screen>cd ~/openstack/my_cloud/config/heat</screen>
   </step>
   <step>
    <para>
     更改 Heat 配置文件。在 heat.conf.j2 中添加此超时值：
    </para>
<screen>rpc_response_timeout=300</screen>
    <para>
     提交您的更改
    </para>
<screen>git commit -a -m "some message"</screen>
   </step>
   <step>
    <para>
     前往 ansible 目录并运行以下剧本：
    </para>
<screen>cd ~/openstack/ardana/ansible
ansible-playbook -i hosts/localhost config-processor-run.yml
ansible-playbook -i hosts/localhost ready-deployment.yml</screen>
   </step>
   <step>
    <para>
     切换到临时目录并运行 heat-reconfigure：
    </para>
<screen>cd ~/scratch/ansible/next/ardana/ansible
ansible-playbook -i hosts/verb_hosts heat-reconfigure.yml</screen>
   </step>
   <step>
    <para>
     从数据库中清除已删除堆栈的记录。首先删除所有处于失败状态的堆栈。然后执行以下操作
    </para>
<screen>sudo /opt/stack/venv/heat-20151116T000451Z/bin/python2
/opt/stack/service/heat-engine/venv/bin/heat-manage
--config-file /opt/stack/service/heat-engine-20151116T000451Z/etc/heat/heat.conf
--config-file /opt/stack/service/heat-engine-20151116T000451Z/etc/heat/engine.conf purge_deleted 0</screen>
   </step>
  </procedure>
 </section>
 <section xml:id="hrat.stack.create.errors">
  <title>一般 Heat 堆栈创建错误</title>
  <para>
   在 Hea t中，通常在发生超时时，意味着底层资源服务（如 Nova，Neutron 或 Cinder）无法完成所需的操作。无论基础服务报告何种错误，Heat 都会将其报告回来。因此，在 Heat 堆栈创建超时的情况下，您应该查看底层服务的日志，尤其是 Nova 服务，以了解超时的原因。
  </para>
 </section>
 <section xml:id="heat_stack_create_failure">
  <title>多个 Heat 堆栈创建失败</title>
  <para>
   Monasca AlarmDefinition 资源，<literal>OS::Monasca::AlarmDefinition</literal> 被用于 Heat 自动缩放，包含可选属性 <emphasis role="bold">name</emphasis>  可以用于定义警报名称。如果在 Heat 模板中指定了此可选属性，则此名称在系统的同一项目中必须是唯一的。否则，使用此 Heat 模板创建的多个 Heat 堆栈将失败，并发生以下冲突：
  </para>
<screen>| cpu_alarm_low  | 5fe0151b-5c6a-4a54-bd64-67405336a740 | HTTPConflict: resources.cpu_alarm_low: An alarm definition already exists for project / tenant: 835d6aeeb36249b88903b25ed3d2e55a named: CPU utilization less than 15 percent  | CREATE_FAILED  | 2016-07-29T10:28:47 |</screen>
  <para>
   这是因为 Monasca 在 Heat 模板中定义时使用此名称属性注册警报定义名称。此名称必须是唯一的。
  </para>
  <para>
   要避免此问题，如果要在模板中使用此属性定义警报名称，则必须确保此名称在系统中的项目中是唯一的。否则，您可以在模板中保留此可选属性。在这种情况下，系统将在 Heat 堆栈创建期间自动创建唯一的警报名称。
  </para>
 </section>
</section>
